import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'], // All possible weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body>{children}</body> */}
      <body className={lato.className}>{children}</body>
    </html>
  );
}
