import { Lato } from "next/font/google";

export const MAX_POST_TITLE_LEN = 100;
export const MAX_POST_CONTENT_LEN = 5000;
export const MAX_POST_DISABILITY_TAGS = 5;

export const PAGINATION_LIMIT = 10;

export const FOCUS_FONT = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

export const LOCATIONS: string[] = [
  "Atlanta",
  "Augusta",
  "Columbus",
  "Savannah",
  "Athens",
  "Sandy Springs",
  "Roswell",
  "Macon",
  "Johns Creek",
  "Albany",
  "Warner Robins",
  "Alpharetta",
  "Marietta",
  "Valdosta",
  "Smyrna",
  "Dunwoody",
  "Rome",
  "Peachtree City",
  "Gainesville",
  "East Point",
  "Hinesville",
  "Dalton",
  "Newnan",
  "Milton",
  "Douglasville",
  "Kennesaw",
  "LaGrange",
  "Statesboro",
  "Lawrenceville",
  "Duluth",
  "Stockbridge",
  "Cartersville",
  "Canton",
  "Brunswick",
  "Griffin",
  "Acworth",
  "Pooler",
  "Snellville",
  "Forest Park",
  "McDonough",
  "Sugar Hill",
  "Suwanee",
  "Thomasville",
  "St. Marys",
  "Tifton",
  "Fayetteville",
  "Norcross",
  "Union City",
  "Riverdale",
  "Lilburn",
  "Villa Rica",
  "Powder Springs",
  "Covington",
  "College Park",
  "Fairburn",
  "Winder",
  "Buford",
  "Dublin",
  "Conyers",
  "Perry",
  "Kingsland",
  "Tucker",
  "Monroe",
  "Cordele",
  "Chamblee",
  "Moultrie",
  "Cumming",
  "Carrollton",
  "Waycross",
  "Calhoun",
  "Americus",
  "Bainbridge",
  "Vidalia",
  "Jesup",
  "Loganville",
  "Garden City",
  "Cedartown",
  "Fort Oglethorpe",
  "Blakely",
  "Morrow",
  "Thomaston",
  "Fort Valley",
  "Bremen",
  "Ellijay",
  "Commerce",
  "Hartwell",
  "Folkston",
  "Hogansville",
  "Hawkinsville",
  "Lincolnton",
  "Louisville",
  "Ludowici",
  "Manchester",
  "Monticello",
  "Mount Vernon",
  "Ocilla",
  "Reidsville",
  "Swainsboro",
  "Washington"
];
