 /**
 * Checks if the provided text contains any profane words
 * from the specified list, ensuring that they are matched as whole words.
 *
 * @param {string} text - The content generated by the user to be checked for profanity.
 * @param {string[]} profanities - An array containing the profane words to check against.
 * @return {string[]} - An array of found profanities; empty if none are found.
 */
export function containsProfanity(text : string, profanities : string[]) {
    const wordsFound = []

    for (const profanity of profanities) {
      const regex = new RegExp(`(^|[^a-zA-Z])${profanity}(?=[^a-zA-Z]|$)`, 'i');
      
      if (regex.test(text)) {
        wordsFound.push(profanity); 
      }
    }
    return wordsFound;
}
